# Uncomment this line to define a global platform for your project
platform :ios, '10.3'
# Uncomment this line if you're using Swift
use_frameworks!
# When adding a Pod please also add the version to it

source 'https://github.com/CocoaPods/Specs.git'
target 'meet' do
    pod 'Alamofire'
    
    target 'meetTests' do
        inherit! :search_paths
    end
        
#    target 'meetUITests' do
#        inherit! :search_paths
#    end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
